from PyQt5 import QtCore, QtGui, QtWidgets
from geographiques_en_cartesiennes import *
from cartesien_geographiq_iterative import *
from cartesien_geographiq_directe import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Geodesie = QtWidgets.QTabWidget(self.centralwidget)
        self.Geodesie.setGeometry(QtCore.QRect(30, 0, 591, 541))
        self.Geodesie.setStyleSheet("background-color: rgb(64, 181, 173);")
        self.Geodesie.setObjectName("Geodesie")
        self.Page1 = QtWidgets.QWidget()
        self.Page1.setObjectName("Page1")
        self.pushButton = QtWidgets.QPushButton(self.Page1)
        self.pushButton.setGeometry(QtCore.QRect(480, 480, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.next1)
        self.label_119 = QtWidgets.QLabel(self.Page1)
        self.label_119.setGeometry(QtCore.QRect(130, 170, 361, 51))
        self.label_119.setObjectName("label_119")
        self.label_120 = QtWidgets.QLabel(self.Page1)
        self.label_120.setGeometry(QtCore.QRect(130, 230, 231, 16))
        self.label_120.setObjectName("label_120")
        self.label_121 = QtWidgets.QLabel(self.Page1)
        self.label_121.setGeometry(QtCore.QRect(360, 230, 121, 17))
        self.label_121.setObjectName("label_121")
        self.label_122 = QtWidgets.QLabel(self.Page1)
        self.label_122.setGeometry(QtCore.QRect(10, 60, 571, 131))
        self.label_122.setStyleSheet("font: 14pt \"Ubuntu\";\n"
"")
        self.label_122.setObjectName("label_122")
        self.label_7 = QtWidgets.QLabel(self.Page1)
        self.label_7.setGeometry(QtCore.QRect(30, 400, 321, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.Page1)
        self.label_8.setGeometry(QtCore.QRect(130, 270, 271, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.Page1)
        self.label_9.setGeometry(QtCore.QRect(30, 430, 171, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.Page1)
        self.label_10.setGeometry(QtCore.QRect(30, 460, 141, 17))
        self.label_10.setObjectName("label_10")
        self.Geodesie.addTab(self.Page1, "")
        self.Page2 = QtWidgets.QWidget()
        self.Page2.setObjectName("Page2")
        self.pushButton_2 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 480, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.next1)
        self.pushButton_3 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_3.setGeometry(QtCore.QRect(380, 480, 89, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.prev1)
        self.label = QtWidgets.QLabel(self.Page2)
        self.label.setGeometry(QtCore.QRect(60, 140, 81, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Page2)
        self.label_2.setGeometry(QtCore.QRect(60, 220, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Page2)
        self.label_3.setGeometry(QtCore.QRect(60, 310, 67, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Page2)
        self.label_4.setGeometry(QtCore.QRect(390, 140, 141, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Page2)
        self.label_5.setGeometry(QtCore.QRect(390, 220, 131, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.Page2)
        self.label_6.setGeometry(QtCore.QRect(400, 310, 131, 17))
        self.label_6.setObjectName("label_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.Page2)
        self.textBrowser.setGeometry(QtCore.QRect(330, 170, 71, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.Page2)
        self.textBrowser_2.setGeometry(QtCore.QRect(410, 170, 71, 41))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.Page2)
        self.textBrowser_3.setGeometry(QtCore.QRect(490, 170, 71, 41))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.Page2)
        self.textBrowser_4.setGeometry(QtCore.QRect(330, 250, 71, 41))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.Page2)
        self.textBrowser_5.setGeometry(QtCore.QRect(410, 250, 71, 41))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.Page2)
        self.textBrowser_6.setGeometry(QtCore.QRect(490, 250, 71, 41))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.Page2)
        self.textBrowser_7.setGeometry(QtCore.QRect(330, 340, 151, 41))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textEdit = QtWidgets.QTextEdit(self.Page2)
        self.textEdit.setGeometry(QtCore.QRect(10, 170, 131, 41))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.Page2)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 250, 131, 41))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.Page2)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 340, 131, 41))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_13 = QtWidgets.QLabel(self.Page2)
        self.label_13.setGeometry(QtCore.QRect(400, 160, 16, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.Page2)
        self.label_14.setGeometry(QtCore.QRect(480, 160, 16, 17))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.Page2)
        self.label_15.setGeometry(QtCore.QRect(560, 160, 16, 17))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.Page2)
        self.label_16.setGeometry(QtCore.QRect(560, 240, 16, 17))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.Page2)
        self.label_17.setGeometry(QtCore.QRect(480, 240, 16, 17))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.Page2)
        self.label_18.setGeometry(QtCore.QRect(400, 240, 16, 17))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.Page2)
        self.label_19.setGeometry(QtCore.QRect(150, 180, 67, 17))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.Page2)
        self.label_20.setGeometry(QtCore.QRect(150, 260, 67, 17))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.Page2)
        self.label_21.setGeometry(QtCore.QRect(150, 350, 67, 17))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.Page2)
        self.label_22.setGeometry(QtCore.QRect(490, 350, 21, 17))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.Page2)
        self.label_23.setGeometry(QtCore.QRect(470, 220, 51, 17))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.Page2)
        self.label_24.setGeometry(QtCore.QRect(480, 140, 51, 17))
        self.label_24.setObjectName("label_24")
        self.pushButton_13 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_13.setGeometry(QtCore.QRect(210, 260, 89, 25))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_13.clicked.connect(self.transformation1)
        self.label_49 = QtWidgets.QLabel(self.Page2)
        self.label_49.setGeometry(QtCore.QRect(10, 0, 571, 81))
        self.label_49.setObjectName("label_49")
        self.label_53 = QtWidgets.QLabel(self.Page2)
        self.label_53.setGeometry(QtCore.QRect(220, 70, 121, 16))
        self.label_53.setObjectName("label_53")
        self.Geodesie.addTab(self.Page2, "")
        self.Page3 = QtWidgets.QWidget()
        self.Page3.setObjectName("Page3")
        self.pushButton_4 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_4.setGeometry(QtCore.QRect(480, 480, 89, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.next1)
        self.pushButton_5 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_5.setGeometry(QtCore.QRect(380, 480, 89, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.prev1)
        self.label_50 = QtWidgets.QLabel(self.Page3)
        self.label_50.setGeometry(QtCore.QRect(10, 0, 571, 81))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.Page3)
        self.label_51.setGeometry(QtCore.QRect(220, 70, 131, 16))
        self.label_51.setObjectName("label_51")
        self.textBrowser_15 = QtWidgets.QTextBrowser(self.Page3)
        self.textBrowser_15.setGeometry(QtCore.QRect(490, 250, 71, 41))
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.label_25 = QtWidgets.QLabel(self.Page3)
        self.label_25.setGeometry(QtCore.QRect(560, 240, 16, 17))
        self.label_25.setObjectName("label_25")
        self.textEdit_4 = QtWidgets.QTextEdit(self.Page3)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 340, 131, 41))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_26 = QtWidgets.QLabel(self.Page3)
        self.label_26.setGeometry(QtCore.QRect(150, 260, 67, 17))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.Page3)
        self.label_27.setGeometry(QtCore.QRect(480, 140, 61, 17))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.Page3)
        self.label_28.setGeometry(QtCore.QRect(390, 140, 141, 17))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.Page3)
        self.label_29.setGeometry(QtCore.QRect(400, 310, 131, 17))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.Page3)
        self.label_30.setGeometry(QtCore.QRect(60, 220, 67, 17))
        self.label_30.setObjectName("label_30")
        self.textBrowser_16 = QtWidgets.QTextBrowser(self.Page3)
        self.textBrowser_16.setGeometry(QtCore.QRect(410, 170, 71, 41))
        self.textBrowser_16.setObjectName("textBrowser_16")
        self.label_31 = QtWidgets.QLabel(self.Page3)
        self.label_31.setGeometry(QtCore.QRect(400, 240, 16, 17))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.Page3)
        self.label_32.setGeometry(QtCore.QRect(480, 160, 16, 17))
        self.label_32.setObjectName("label_32")
        self.textBrowser_17 = QtWidgets.QTextBrowser(self.Page3)
        self.textBrowser_17.setGeometry(QtCore.QRect(330, 250, 71, 41))
        self.textBrowser_17.setObjectName("textBrowser_17")
        self.label_33 = QtWidgets.QLabel(self.Page3)
        self.label_33.setGeometry(QtCore.QRect(60, 140, 81, 17))
        self.label_33.setObjectName("label_33")
        self.textBrowser_34 = QtWidgets.QTextBrowser(self.Page3)
        self.textBrowser_34.setGeometry(QtCore.QRect(330, 170, 71, 41))
        self.textBrowser_34.setObjectName("textBrowser_34")
        self.label_34 = QtWidgets.QLabel(self.Page3)
        self.label_34.setGeometry(QtCore.QRect(390, 220, 131, 17))
        self.label_34.setObjectName("label_34")
        self.textBrowser_35 = QtWidgets.QTextBrowser(self.Page3)
        self.textBrowser_35.setGeometry(QtCore.QRect(490, 170, 71, 41))
        self.textBrowser_35.setObjectName("textBrowser_35")
        self.label_35 = QtWidgets.QLabel(self.Page3)
        self.label_35.setGeometry(QtCore.QRect(150, 180, 67, 17))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.Page3)
        self.label_36.setGeometry(QtCore.QRect(150, 350, 67, 17))
        self.label_36.setObjectName("label_36")
        self.label_113 = QtWidgets.QLabel(self.Page3)
        self.label_113.setGeometry(QtCore.QRect(400, 160, 16, 17))
        self.label_113.setObjectName("label_113")
        self.label_114 = QtWidgets.QLabel(self.Page3)
        self.label_114.setGeometry(QtCore.QRect(470, 220, 51, 17))
        self.label_114.setObjectName("label_114")
        self.label_115 = QtWidgets.QLabel(self.Page3)
        self.label_115.setGeometry(QtCore.QRect(480, 240, 16, 17))
        self.label_115.setObjectName("label_115")
        self.label_116 = QtWidgets.QLabel(self.Page3)
        self.label_116.setGeometry(QtCore.QRect(560, 160, 16, 17))
        self.label_116.setObjectName("label_116")
        self.textBrowser_36 = QtWidgets.QTextBrowser(self.Page3)
        self.textBrowser_36.setGeometry(QtCore.QRect(330, 340, 151, 41))
        self.textBrowser_36.setObjectName("textBrowser_36")
        self.textEdit_5 = QtWidgets.QTextEdit(self.Page3)
        self.textEdit_5.setGeometry(QtCore.QRect(10, 250, 131, 41))
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_117 = QtWidgets.QLabel(self.Page3)
        self.label_117.setGeometry(QtCore.QRect(60, 310, 67, 17))
        self.label_117.setObjectName("label_117")
        self.label_118 = QtWidgets.QLabel(self.Page3)
        self.label_118.setGeometry(QtCore.QRect(490, 350, 67, 17))
        self.label_118.setObjectName("label_118")
        self.textEdit_6 = QtWidgets.QTextEdit(self.Page3)
        self.textEdit_6.setGeometry(QtCore.QRect(10, 170, 131, 41))
        self.textEdit_6.setObjectName("textEdit_6")
        self.pushButton_14 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_14.setGeometry(QtCore.QRect(210, 260, 89, 25))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_14.clicked.connect(self.transformation2)
        self.textBrowser_37 = QtWidgets.QTextBrowser(self.Page3)
        self.textBrowser_37.setGeometry(QtCore.QRect(410, 250, 71, 41))
        self.textBrowser_37.setObjectName("textBrowser_37")
        self.label_124 = QtWidgets.QLabel(self.Page3)
        self.label_124.setGeometry(QtCore.QRect(480, 140, 51, 17))
        self.label_124.setObjectName("label_124")
        self.Geodesie.addTab(self.Page3, "")
        self.Page4 = QtWidgets.QWidget()
        self.Page4.setObjectName("Page4")
        self.label_37 = QtWidgets.QLabel(self.Page4)
        self.label_37.setGeometry(QtCore.QRect(80, 250, 16, 17))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.Page4)
        self.label_38.setGeometry(QtCore.QRect(470, 220, 21, 17))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.Page4)
        self.label_39.setGeometry(QtCore.QRect(160, 140, 16, 17))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.Page4)
        self.label_40.setGeometry(QtCore.QRect(470, 120, 31, 17))
        self.label_40.setObjectName("label_40")
        self.textEdit_11 = QtWidgets.QTextEdit(self.Page4)
        self.textEdit_11.setGeometry(QtCore.QRect(90, 260, 71, 41))
        self.textEdit_11.setObjectName("textEdit_11")
        self.textEdit_12 = QtWidgets.QTextEdit(self.Page4)
        self.textEdit_12.setGeometry(QtCore.QRect(90, 150, 71, 41))
        self.textEdit_12.setObjectName("textEdit_12")
        self.textEdit_13 = QtWidgets.QTextEdit(self.Page4)
        self.textEdit_13.setGeometry(QtCore.QRect(10, 390, 191, 41))
        self.textEdit_13.setObjectName("textEdit_13")
        self.textBrowser_18 = QtWidgets.QTextBrowser(self.Page4)
        self.textBrowser_18.setGeometry(QtCore.QRect(400, 260, 141, 41))
        self.textBrowser_18.setObjectName("textBrowser_18")
        self.textEdit_14 = QtWidgets.QTextEdit(self.Page4)
        self.textEdit_14.setGeometry(QtCore.QRect(10, 260, 71, 41))
        self.textEdit_14.setObjectName("textEdit_14")
        self.label_41 = QtWidgets.QLabel(self.Page4)
        self.label_41.setGeometry(QtCore.QRect(60, 220, 81, 17))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.Page4)
        self.label_42.setGeometry(QtCore.QRect(60, 110, 91, 17))
        self.label_42.setObjectName("label_42")
        self.pushButton_16 = QtWidgets.QPushButton(self.Page4)
        self.pushButton_16.setGeometry(QtCore.QRect(380, 480, 89, 25))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_16.clicked.connect(self.prev1)
        self.label_43 = QtWidgets.QLabel(self.Page4)
        self.label_43.setGeometry(QtCore.QRect(60, 360, 67, 17))
        self.label_43.setObjectName("label_43")
        self.pushButton_17 = QtWidgets.QPushButton(self.Page4)
        self.pushButton_17.setGeometry(QtCore.QRect(280, 270, 89, 25))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_17.clicked.connect(self.transformation3)
        self.label_44 = QtWidgets.QLabel(self.Page4)
        self.label_44.setGeometry(QtCore.QRect(80, 140, 16, 17))
        self.label_44.setObjectName("label_44")
        self.textEdit_15 = QtWidgets.QTextEdit(self.Page4)
        self.textEdit_15.setGeometry(QtCore.QRect(170, 260, 71, 41))
        self.textEdit_15.setObjectName("textEdit_15")
        self.label_45 = QtWidgets.QLabel(self.Page4)
        self.label_45.setGeometry(QtCore.QRect(470, 320, 21, 17))
        self.label_45.setObjectName("label_45")
        self.textBrowser_19 = QtWidgets.QTextBrowser(self.Page4)
        self.textBrowser_19.setGeometry(QtCore.QRect(400, 360, 141, 41))
        self.textBrowser_19.setObjectName("textBrowser_19")
        self.textEdit_16 = QtWidgets.QTextEdit(self.Page4)
        self.textEdit_16.setGeometry(QtCore.QRect(170, 150, 71, 41))
        self.textEdit_16.setObjectName("textEdit_16")
        self.label_46 = QtWidgets.QLabel(self.Page4)
        self.label_46.setGeometry(QtCore.QRect(240, 140, 16, 17))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.Page4)
        self.label_47.setGeometry(QtCore.QRect(240, 250, 16, 17))
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.Page4)
        self.label_48.setGeometry(QtCore.QRect(160, 250, 16, 17))
        self.label_48.setObjectName("label_48")
        self.textEdit_17 = QtWidgets.QTextEdit(self.Page4)
        self.textEdit_17.setGeometry(QtCore.QRect(10, 150, 71, 41))
        self.textEdit_17.setObjectName("textEdit_17")
        self.textBrowser_20 = QtWidgets.QTextBrowser(self.Page4)
        self.textBrowser_20.setGeometry(QtCore.QRect(400, 150, 141, 41))
        self.textBrowser_20.setObjectName("textBrowser_20")
        self.label_52 = QtWidgets.QLabel(self.Page4)
        self.label_52.setGeometry(QtCore.QRect(10, -30, 571, 131))
        self.label_52.setObjectName("label_52")
        self.label_54 = QtWidgets.QLabel(self.Page4)
        self.label_54.setGeometry(QtCore.QRect(150, 110, 67, 17))
        self.label_54.setObjectName("label_54")
        self.label_56 = QtWidgets.QLabel(self.Page4)
        self.label_56.setGeometry(QtCore.QRect(210, 400, 67, 17))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.Page4)
        self.label_57.setGeometry(QtCore.QRect(550, 160, 31, 17))
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.Page4)
        self.label_58.setGeometry(QtCore.QRect(550, 270, 31, 17))
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.Page4)
        self.label_59.setGeometry(QtCore.QRect(550, 370, 21, 17))
        self.label_59.setObjectName("label_59")
        self.label_123 = QtWidgets.QLabel(self.Page4)
        self.label_123.setGeometry(QtCore.QRect(140, 220, 67, 17))
        self.label_123.setObjectName("label_123")
        self.Geodesie.addTab(self.Page4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Geodesie.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Suivant"))
        self.label_119.setText(_translate("MainWindow", "Module : Géodésie et Localisation par satellites (GPS)"))
        self.label_120.setText(_translate("MainWindow", "L\'application est développée par :"))
        self.label_121.setText(_translate("MainWindow", "CHAMMAM Anas"))
        self.label_122.setText(_translate("MainWindow", "Transformation des coordoonées géographiques et cartésiennes"))
        self.label_7.setText(_translate("MainWindow", "Ellipsoïde géodésique : Clarke 1880"))
        self.label_8.setText(_translate("MainWindow", "Encadrée par : Pr. Hakim Boulaassal"))
        self.label_9.setText(_translate("MainWindow", "a(m)=6378249.145"))
        self.label_10.setText(_translate("MainWindow", "b(m)=6356515.0"))
        self.Geodesie.setTabText(self.Geodesie.indexOf(self.Page1), _translate("MainWindow", "Page 1"))
        self.pushButton_2.setText(_translate("MainWindow", "Suivant"))
        self.pushButton_3.setText(_translate("MainWindow", "Précedent"))
        self.label.setText(_translate("MainWindow", "X"))
        self.label_2.setText(_translate("MainWindow", "Y"))
        self.label_3.setText(_translate("MainWindow", "Z"))
        self.label_4.setText(_translate("MainWindow", "Longitude λ"))
        self.label_5.setText(_translate("MainWindow", "Latitude φ"))
        self.label_6.setText(_translate("MainWindow", "Hauteur h"))
        self.label_13.setText(_translate("MainWindow", "°"))
        self.label_14.setText(_translate("MainWindow", "\'"))
        self.label_15.setText(_translate("MainWindow", "\""))
        self.label_16.setText(_translate("MainWindow", "\""))
        self.label_17.setText(_translate("MainWindow", "\'"))
        self.label_18.setText(_translate("MainWindow", "°"))
        self.label_19.setText(_translate("MainWindow", "m"))
        self.label_20.setText(_translate("MainWindow", "m"))
        self.label_21.setText(_translate("MainWindow", "m"))
        self.label_22.setText(_translate("MainWindow", "m"))
        self.label_23.setText(_translate("MainWindow", "en dms"))
        self.label_24.setText(_translate("MainWindow", "en dms"))
        self.pushButton_13.setText(_translate("MainWindow", "Convertir"))
        self.label_49.setText(_translate("MainWindow", "Transformation des coordonnées cartésiennes en coordonnées géographiques"))
        self.label_53.setText(_translate("MainWindow", "Méthode directe"))
        self.Geodesie.setTabText(self.Geodesie.indexOf(self.Page2), _translate("MainWindow", "Page 2"))
        self.pushButton_4.setText(_translate("MainWindow", "Suivant"))
        self.pushButton_5.setText(_translate("MainWindow", "Précedent"))
        self.label_50.setText(_translate("MainWindow", "Transformation des coordonnées cartésiennes en coordonnées géographiques"))
        self.label_51.setText(_translate("MainWindow", "Méthode itérative"))
        self.label_25.setText(_translate("MainWindow", "\""))
        self.label_26.setText(_translate("MainWindow", "m"))
        self.label_27.setText(_translate("MainWindow", "en dms"))
        self.label_28.setText(_translate("MainWindow", "Longitude λ"))
        self.label_29.setText(_translate("MainWindow", "Hauteur h"))
        self.label_30.setText(_translate("MainWindow", "Y"))
        self.label_31.setText(_translate("MainWindow", "°"))
        self.label_32.setText(_translate("MainWindow", "\'"))
        self.label_33.setText(_translate("MainWindow", "X"))
        self.label_34.setText(_translate("MainWindow", "Latitude φ"))
        self.label_35.setText(_translate("MainWindow", "m"))
        self.label_36.setText(_translate("MainWindow", "m"))
        self.label_113.setText(_translate("MainWindow", "°"))
        self.label_114.setText(_translate("MainWindow", "en dms"))
        self.label_115.setText(_translate("MainWindow", "\'"))
        self.label_116.setText(_translate("MainWindow", "\""))
        self.label_117.setText(_translate("MainWindow", "Z"))
        self.label_118.setText(_translate("MainWindow", "m"))
        self.pushButton_14.setText(_translate("MainWindow", "Convertir"))
        self.label_124.setText(_translate("MainWindow", "en dms"))
        self.Geodesie.setTabText(self.Geodesie.indexOf(self.Page3), _translate("MainWindow", "Page 3"))
        self.label_37.setText(_translate("MainWindow", "°"))
        self.label_38.setText(_translate("MainWindow", "Y"))
        self.label_39.setText(_translate("MainWindow", "\'"))
        self.label_40.setText(_translate("MainWindow", "X"))
        self.label_41.setText(_translate("MainWindow", "Latitude φ"))
        self.label_42.setText(_translate("MainWindow", "Longitude λ"))
        self.pushButton_16.setText(_translate("MainWindow", "Précedent"))
        self.label_43.setText(_translate("MainWindow", "Hauteur h"))
        self.pushButton_17.setText(_translate("MainWindow", "Convertir"))
        self.label_44.setText(_translate("MainWindow", "°"))
        self.label_45.setText(_translate("MainWindow", "Z"))
        self.label_46.setText(_translate("MainWindow", "\""))
        self.label_47.setText(_translate("MainWindow", "\""))
        self.label_48.setText(_translate("MainWindow", "\'"))
        self.label_52.setText(_translate("MainWindow", "Transformation des coordonnées géographiques en coordonnées cartesiennes"))
        self.label_54.setText(_translate("MainWindow", "en dms"))
        self.label_56.setText(_translate("MainWindow", "m"))
        self.label_57.setText(_translate("MainWindow", "m"))
        self.label_58.setText(_translate("MainWindow", "m"))
        self.label_59.setText(_translate("MainWindow", "m"))
        self.label_123.setText(_translate("MainWindow", "en dms"))
        self.Geodesie.setTabText(self.Geodesie.indexOf(self.Page4), _translate("MainWindow", "Page 4"))
    def next1(self):
        QtWidgets.QTabWidget.setCurrentIndex(self.Geodesie,self.Geodesie.currentIndex()+1)
    def prev1(self):
        QtWidgets.QTabWidget.setCurrentIndex(self.Geodesie,self.Geodesie.currentIndex()-1)
    def transformation1(self):
        X = float(self.textEdit.toPlainText())
        Y=float(self.textEdit_2.toPlainText())
        Z=float(self.textEdit_3.toPlainText())
        malist=[]
        malist=cartesien_geographiq_directe(X,Y,Z)

        self.textBrowser.setText(str(malist[0][0]))
        self.textBrowser_2.setText(str(malist[0][1]))
        self.textBrowser_3.setText(str(malist[0][2]))
        self.textBrowser_4.setText(str(malist[1][0]))
        self.textBrowser_5.setText(str(malist[1][1]))
        self.textBrowser_6.setText(str(malist[1][2]))
        self.textBrowser_7.setText(str(malist[2]))
    def transformation2(self):
        X = float(self.textEdit_6.toPlainText())
        Y=float(self.textEdit_5.toPlainText())
        Z=float(self.textEdit_4.toPlainText())
        malist=[]
        malist=cartesien_geographiq_iterative(X,Y,Z)
        self.textBrowser_34.setText(str(malist[0][0]))
        self.textBrowser_16.setText(str(malist[0][1]))
        self.textBrowser_35.setText(str(malist[0][2]))
        self.textBrowser_17.setText(str(malist[1][0]))
        self.textBrowser_37.setText(str(malist[1][1]))
        self.textBrowser_15.setText(str(malist[1][2]))
        self.textBrowser_36.setText(str(malist[2]))

    def transformation3(self):
        D1 = float(self.textEdit_17.toPlainText())
        M1 = float(self.textEdit_12.toPlainText())
        S1 = float(self.textEdit_16.toPlainText())
        D2 = float(self.textEdit_14.toPlainText())
        M2 = float(self.textEdit_11.toPlainText())
        S2 = float(self.textEdit_15.toPlainText())
        h = float(self.textEdit_13.toPlainText())

        malist = []
        malist = geographiques_en_cartesiennes(D1, M1, S1, D2, M2, S2, h)
        X=malist[0]
        Y=malist[1]
        Z=malist[2]
        self.textBrowser_20.setText(str(X))
        self.textBrowser_18.setText(str(Y))
        self.textBrowser_19.setText(str(Z))